LibraryManagementSystem/Controllers/BookIssueReturnController.cs
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Service;
using System;
using System.Web.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class BookIssueReturnController : Controller
    {
        BookIssueReturnService bookIssueReturnService;
        BookService bookService;
        MemberService memberService;
        AssessionMappingService assessionMappingService;
        public BookIssueReturnController()
        {
            bookIssueReturnService = new BookIssueReturnService();
            bookService = new BookService();
            memberService = new MemberService();
            assessionMappingService = new AssessionMappingService();
        }
        // GET: BookIssueReturn
        public ActionResult Index()
        {
            var data = new MemberModel();
            data.ToIssueBookModel = new BookModel();
            data.ToIssueBookModel.BookIssueList = bookService.DisplayDataComboList();
            data.IssuedBookList = new System.Collections.Generic.List<BookIssueReturnModel>();
            return View(data);
        }
        [HttpPost]
        public ActionResult Issue(Models.BookIssueReturnModel bookIssueReturnModel)
        {
            bookIssueReturnModel.IssueDate = DateTime.Now;
            bookIssueReturnModel.DueDate = DateTime.Now.AddDays(15);
            bookIssueReturnModel.Status = 1;
           // bookIssueReturnModel.NoOfIssuedBook = bookIssueReturnService
               //     .DisplayDataByMemberId(bookIssueReturnModel.MemberID).Count;
            if (bookIssueReturnModel.NoOfIssuedBook < 3)
            {
                bookIssueReturnService.SaveData(bookIssueReturnModel);
                assessionMappingService.UpdateBookStatus((int)bookIssueReturnModel.AssessionID, 1);

                ViewBag.ResultMessage = "Issued Successfully";

            }
            else
            {
                ViewBag.ResultMessage = "You cannot Issue More then 3 books";

            }

            var dataMember = new MemberModel();
            dataMember = LoadModel((int)bookIssueReturnModel.MemberID);

            return RedirectToAction("Search", new { MemberID=dataMember.MemberID });

        }

        //[HttpGet]
        //public ActionResult Search()
        //{
        //    return View("_SearchPartial", new MemberModel());
        //}
        [HttpGet]
        public ActionResult Search(MemberModel model)
        {
            model = LoadModel(model.MemberID);

            return View("Index", model);
        }



        public ActionResult Issue()
        {
            return View("_IssueBook", new BookModel());
        }


        public ActionResult Edit(int id, int memberID)
        {
            bookIssueReturnService.UpdateReturnBookData(id, memberID);
            assessionMappingService.UpdateBookStatus(id, 0);

            return View("Index", LoadModel(memberID));
        }
       
        private MemberModel LoadModel(int MemberId)
        {
            MemberModel model = new MemberModel();
            model = memberService.GetData(MemberId);
            // model.MemberName = mem;
            model.ToIssueBookModel = new BookModel();
            model.ToIssueBookModel.MemberId = model.MemberID;
            model.ToIssueBookModel.BookIssueList = bookService.DisplayDataComboList();
            model.IssuedBookList = bookIssueReturnService.DisplayDataByMemberId(model.MemberID);
            //to count Issued no of books
            if (model.IssuedBookList != null)
            {
                model.ToIssueBookModel.NoOfIssuedBook = model.IssuedBookList.Count;
                model.NoOfIssuedBook = model.IssuedBookList.Count;
            }
            else
            {
                model.ToIssueBookModel.NoOfIssuedBook = 0;
                model.NoOfIssuedBook = 0;
            }
            model.ToIssueBookModel.MemberId = model.MemberID;

            return model;

        }
    }
}

LibraryManagementSystem/Views/BookIssueReturn/Delete.cshtml
@model LibraryManagementSystem.Models.BookIssueReturnModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookIssueReturnModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookIssueReturnID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookIssueReturnID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssessionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssessionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LateDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LateDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FineAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FineAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StaffMemberID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffMemberID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryManagementSystem/Views/BookIssueReturn/DisplayList.cshtml
@model IEnumerable<LibraryManagementSystem.Models.BookIssueReturnModel>

@{
    ViewBag.Title = "DisplayList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookIssueReturnID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MemberID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssessionID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LateDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FineAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StaffMemberID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remarks)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BookIssueReturnID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MemberID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssessionID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IssueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LateDays)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FineAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StaffMemberID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Remarks)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

LibraryManagementSystem/Views/BookIssueReturn/Edit.cshtml
@model LibraryManagementSystem.Models.BookIssueReturnModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BookIssueReturnModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookIssueReturnID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookIssueReturnID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookIssueReturnID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssessionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssessionID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssessionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LateDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LateDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LateDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FineAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FineAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FineAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffMemberID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffMemberID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffMemberID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LibraryManagementSystem/Views/BookIssueReturn/Index.cshtml
@model LibraryManagementSystem.Models.MemberModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_SearchPartial", Model);
    Html.RenderPartial("_IssueBook", Model.ToIssueBookModel);

    if(Model.IssuedBookList.Count>0)
    {
        Html.RenderPartial("_ListIssuedBook", Model.IssuedBookList);

    }

}

LibraryManagementSystem/Views/BookIssueReturn/_IssueBook.cshtml
@model LibraryManagementSystem.Models.BookModel


@using (Html.BeginForm("Issue", "BookIssueReturn", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Book Issue</h4>
    <hr />
    @Html.HiddenFor(model => model.MemberId)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                @Html.Label("No Of Book Issued", htmlAttributes: new { @class = "control-label col-md-11" })

            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.NoOfIssuedBook, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.NoOfIssuedBook, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.AssessionID, htmlAttributes: new { @class = "control-label col-md-11" })

            </div>
            <div class="col-md-6">
                @Html.DropDownListFor(x => Model.AssessionID, new SelectList(Model.BookIssueList, "Value", "Text"), htmlAttributes: new { @class = "form-control", @id = "Region" })
                @Html.ValidationMessageFor(model => model.AssessionID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })

            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Issue" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <h3>@ViewBag.ResultMessage</h3>
            </div>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManagementSystem/Views/BookIssueReturn/_ListIssuedBook.cshtml
@model IEnumerable<LibraryManagementSystem.Models.BookIssueReturnModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.LateDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FineAmount)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Remarks)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BookDescription)
        </td>

        <td>
            @item.IssueDate.Value.ToShortDateString()
            @*@Html.DisplayFor(modelItem => item.IssueDate)*@
        </td>

        <td>
            @item.DueDate.Value.ToShortDateString()
            @*@Html.DisplayFor(modelItem => item.DueDate)*@
        </td>
        <td>
            @item.ReturnDate.Value.ToShortDateString()
            @*@Html.DisplayFor(modelItem => item.ReturnDate)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LateDays)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FineAmount)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Remarks)
        </td>
        <td>
            @Html.ActionLink("Return Books", "Edit", new { id=item.AssessionID,memberID=item.MemberID }) |
            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>

LibraryManagementSystem/Views/BookIssueReturn/_SearchPartial.cshtml
@model LibraryManagementSystem.Models.MemberModel

@using (Html.BeginForm("Search", "BookIssueReturn", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Book Issue and Return</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        @Html.LabelFor(model => model.MemberID, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MemberID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MemberID, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class=" col-md-4">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
            </div>
        </div>




    </div>
</div>
        }