LibraryManagementSystem/Controllers/BookCategoryController.cs
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class BookCategoryController : Controller
    {
        BookCategoryService bookCategoryService;
        public BookCategoryController()
        {
            bookCategoryService = new BookCategoryService();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BookCategoryModel model)
        {
            bookCategoryService.SaveData(model);
            return RedirectToAction("Index");
        }
        // GET: BookCategory
        public ActionResult Index()
        {
            var data = bookCategoryService.DisplayData();
            return View(data);
        }
        [HttpPost]
        public ActionResult Index(Models.BookCategoryModel bookCategoryModel)
        {
            bookCategoryService.SaveData(bookCategoryModel);
            var data = bookCategoryService.DisplayData();
            return View(data);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = bookCategoryService.GetData(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(BookCategoryModel model)
        {
            bookCategoryService.UpdateData(model);
            var dataList = bookCategoryService.DisplayData();
            return View("DisplayList", dataList);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            bookCategoryService.DeleteData(id);
            var dataList = bookCategoryService.DisplayData();
            return View("DisplayList", dataList);
        }
        public ActionResult _DisplayPartialData()
        {
            var dataList = bookCategoryService.DisplayData();
            return View(dataList);
        }
    }
}

LibraryManagementSystem/Controllers/MemberCategoryController.cs
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class MemberCategoryController : Controller
    {
        MemberCategoryService memberCategoryService;
        public MemberCategoryController()
        {
            memberCategoryService = new MemberCategoryService();
        }

        // GET: MemberCategory
        public ActionResult Index()
        {
            var data = memberCategoryService.DisplayData();
            return View(data);
        }
        [HttpPost]
        public ActionResult Index(Models.MemberCategoryModel memberCategoryModel)
        {
            memberCategoryService.SaveData(memberCategoryModel);
            var data = memberCategoryService.DisplayData();
            return View(data);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = memberCategoryService.GetData(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(MemberCategoryModel model)
        {
            memberCategoryService.UpdateData(model);
            var dataList = memberCategoryService.DisplayData();
            return View("DisplayList", dataList);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            memberCategoryService.DeleteData(id);
            var dataList = memberCategoryService.DisplayData();
            return View("DisplayList", dataList);
        }
        public ActionResult _DisplayPartialData()
        {
            var dataList = memberCategoryService.DisplayData();
            return View(dataList);
        }
    }
}

LibraryManagementSystem/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Online Library Management System</title>
    @Styles.Render("~/bundles/css")
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Dashboard <sup>2</sup></div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Menus
            </div>
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Entry</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="@Url.Action("Index","MemberCategory")" >Member Category</a>
                        <a class="collapse-item" href="@Url.Action("Index","BookCategory")">Book Category</a>
                        <a class="collapse-item" href="@Url.Action("Index","MemberCategory")">Members</a>
                        <a class="collapse-item" href="@Url.Action("Index","BookCategory")">Books</a>
                        <a class="collapse-item" href="@Url.Action("Index","AuthorCategory")">Authors</a>
                        <a class="collapse-item" href="@Url.Action("Index","FineCategory")">Fine Settings</a>




                    </div>
                </div>
            </li>
            <!-- Nav Item - Utilities Collapse Menu -->
           
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>
            <!-- Nav Item - Pages Collapse Menu -->
            <!-- Nav Item - Charts -->
          
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                @RenderBody()
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                   
                    <!-- Topbar Navbar -->
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ismt college</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    @Scripts.Render("~/bundles/js")
</body>
</html>